// Read-only Unity scene audit. Does not render or enter Play mode.
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const root='D:/Unity/HTH3 Project/Assets/TherapyGame',folder='Exterior/LivingGarden';
const read=p=>fs.readFileSync(path.join(root,p),'utf8');
const parse=t=>[...t.matchAll(/^--- !u!(\d+) &(-?\d+)\r?\n([\s\S]*?)(?=^--- !u!|$(?![\s\S]))/gm)].map(m=>({type:+m[1],id:m[2],text:m[3]}));
const scalar=(t,k)=>t?.match(new RegExp('^  '+k+': (.*)$','m'))?.[1].trim();
const ref=(t,k)=>scalar(t,k)?.match(/fileID: (-?\d+)/)?.[1];
const guid=p=>read(p+'.meta').match(/guid: (\w+)/)[1];
const docs=parse(read('Scenes/TherapyRoom.unity')),before=parse(read(folder+'/Backups/TherapyRoom_BeforeGardenLife.unity'));
const byID=new Map(docs.map(d=>[d.id,d]));
const scripts=n=>docs.filter(d=>d.type===114&&d.text.includes('guid: '+guid('Runtime/'+n+'.cs')));
const objects=docs.filter(d=>d.type===1),transforms=docs.filter(d=>d.type===4);
const lifeGO=objects.filter(d=>scalar(d.text,'m_Name')==='Living garden');
const lifeTransform=transforms.find(d=>ref(d.text,'m_GameObject')===lifeGO[0]?.id);
const treeIDs=new Set([lifeTransform?.id]);let found=true;while(found){found=false;for(const t of transforms)if(treeIDs.has(ref(t.text,'m_Father'))&&!treeIDs.has(t.id)){treeIDs.add(t.id);found=true;}}
const gameIDs=new Set(transforms.filter(t=>treeIDs.has(t.id)).map(t=>ref(t.text,'m_GameObject')));
const members=docs.filter(d=>gameIDs.has(ref(d.text,'m_GameObject'))),renderers=members.filter(d=>d.type===23);
const life=scripts('WellnessGardenLife')[0],cycle=scripts('WellnessSkyCycle')[0];
const checks=[];const check=(name,ok,detail)=>checks.push({name,ok:!!ok,...(detail===undefined?{}:{detail})});
check('Exactly one additive living-garden group and controller',lifeGO.length===1&&scripts('WellnessGardenLife').length===1&&ref(life?.text,'m_GameObject')===lifeGO[0]?.id);
check('Existing player camera and sky assigned',byID.get(ref(life?.text,'viewer'))?.type===20&&ref(life?.text,'sky')===cycle?.id);
check('Wildlife visibility distance limited to 38 metres',scalar(life?.text,'wildlifeDistance')==='38');
const kinds=[...life.text.matchAll(/- kind: (\d+)/g)].map(m=>+m[1]);
check('Three rabbits two squirrels five birds',kinds.length===10&&kinds.filter(k=>k===0).length===3&&kinds.filter(k=>k===1).length===2&&kinds.filter(k=>k===2).length===5);
check('Forty-five lightweight renderers with no shadow casting',renderers.length===45&&renderers.every(d=>scalar(d.text,'m_CastShadows')==='0'));
check('Only twelve new trunk colliders and no simulations or lights',members.filter(d=>d.type===65).length===12&&!members.some(d=>[20,54,64,108,143,198].includes(d.type)));
const meshFiles=fs.readdirSync(path.join(root,folder,'Meshes')).filter(f=>f.endsWith('.asset'));
check('Twenty-two shared mesh assets',meshFiles.length===22);
const materials=fs.readdirSync(path.join(root,folder,'Materials')).filter(f=>f.endsWith('.mat'));
check('Four shared materials use the garden-life shader',materials.length===4&&materials.every(f=>read(folder+'/Materials/'+f).includes('guid: '+guid(folder+'/Shaders/GardenLife.shader'))));
const source=JSON.parse(read(folder+'/Source/GardenLife.json'));
check('Flower tree and woodland decoration variety',source.plants.length===165&&new Set(source.plants.map(p=>p.type)).size===5&&source.trees.length===12&&source.details.length===39);
check('Original scene records retained except new child link',before.every(d=>byID.has(d.id)));
const gardenTransformID=ref(lifeTransform.text,'m_Father');
const unexpected=before.filter(d=>d.id!==gardenTransformID&&byID.get(d.id)?.text!==d.text);
check('Existing room garden fog water door lighting and interactions untouched',unexpected.length===0,{unexpectedIDs:unexpected.map(d=>d.id)});
check('No change to low-load URP configuration',read('Exterior/Settings/GardenLowLoadURP.asset')===fs.readFileSync('D:/Hack the Hill/Deliverables/TherapyGame/Exterior/Settings/GardenLowLoadURP.asset','utf8'));
check('Unity CPU placement animation and import checks passed',read(folder+'/GardenLifeCheck.txt').includes('PASS: scene raycasts verify animal routes match existing terrain'));
check('One-use import gate completed',read('GardenLifeRequest.txt').trim()==='installed-live-visual-check-pending');
const hash=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');
check('Live model export matches CPU-checked source',hash(path.join(root,folder,'Source/GardenLife.json'))===hash('D:/Hack the Hill/Deliverables/OutdoorGarden/generated/GardenLife.json'));
const result={ok:checks.every(c=>c.ok),method:'Saved-scene and CPU/import checks only; visual quality/performance unverified',checks};
console.log(JSON.stringify(result,null,2));if(!result.ok)process.exitCode=1;
