// Read-only saved-scene verification: no Play, rendering, microphone or network.
const fs=require('node:fs'),path=require('node:path');
const root='D:/Unity/HTH3 Project/Assets/TherapyGame';
const read=p=>fs.readFileSync(path.join(root,p),'utf8');
const parse=text=>[...text.matchAll(/^--- !u!(\d+) &(-?\d+)\r?\n([\s\S]*?)(?=^--- !u!|$(?![\s\S]))/gm)].map(m=>({type:+m[1],id:m[2],text:m[3]}));
const scalar=(text,key)=>text?.match(new RegExp('^  '+key+': (.*)$','m'))?.[1].trim();
const ref=(text,key)=>scalar(text,key)?.match(/fileID: (\d+)/)?.[1];
const guid=p=>read(p+'.meta').match(/guid: (\w+)/)[1];
const docs=parse(read('Scenes/TherapyRoom.unity'));
const before=parse(read('Weather/Backups/TherapyRoom_BeforeWeatherCycle.unity'));
const byID=new Map(docs.map(d=>[d.id,d]));
const scripts=name=>docs.filter(d=>d.type===114&&d.text.includes('guid: '+guid('Runtime/'+name+'.cs')));
const objects=docs.filter(d=>d.type===1);
const cycle=scripts('WellnessSkyCycle')[0],chat=scripts('WellnessVoiceChat')[0],rain=scripts('WellnessRain')[0];
const checks=[];const check=(name,ok,detail)=>checks.push({name,ok:!!ok,...(detail===undefined?{}:{detail})});
check('One linked cycle, preserving voice/rain controllers',scripts('WellnessSkyCycle').length===1&&scripts('WellnessVoiceChat').length===1&&scripts('WellnessRain').length===1&&ref(chat?.text,'skyCycle')===cycle?.id&&ref(cycle?.text,'rain')===rain?.id);
check('12-minute day and 8-minute weather loop',scalar(cycle?.text,'dayMinutes')==='12'&&scalar(cycle?.text,'weatherMinutes')==='8');
check('Automatic daytime/weather enabled, starting at 15:00',scalar(cycle?.text,'hour')==='15'&&scalar(cycle?.text,'timeRuns')==='1'&&scalar(cycle?.text,'weatherMode')==='0');
check('Existing haze and pond renderer linked',byID.has(ref(cycle?.text,'atmosphere'))&&byID.get(ref(cycle?.text,'pondRenderer'))?.type===23);
const sun=byID.get(ref(cycle?.text,'daylight'));
check('Reuses one existing directional light',sun?.type===108&&scalar(sun.text,'m_Type')==='1'&&docs.filter(d=>d.type===108&&scalar(d.text,'m_Type')==='1').length===1&&before.some(d=>d.id===sun.id));
check('All original lights and scene lighting settings unchanged',before.filter(d=>d.type===108||d.type===104||d.type===157).every(d=>byID.get(d.id)?.text===d.text));
check('Sky and cloud materials are serialized references',cycle?.text.includes('guid: '+guid('Weather/Materials/QuietSky.mat'))&&cycle?.text.includes('guid: '+guid('Weather/Materials/SoftCloud.mat')));
check('Weather shaders referenced by their materials',read('Weather/Materials/QuietSky.mat').includes('guid: '+guid('Weather/Shaders/QuietSky.shader'))&&read('Weather/Materials/SoftCloud.mat').includes('guid: '+guid('Weather/Shaders/SoftCloud.shader')));
const clouds=objects.filter(d=>/^Drifting cloud \d\d$/.test(scalar(d.text,'m_Name'))),cloudIDs=new Set(clouds.map(d=>d.id));
const cloudParts=docs.filter(d=>cloudIDs.has(ref(d.text,'m_GameObject')));
check('Sixteen clouds with no colliders or extra lights',clouds.length===16&&!cloudParts.some(d=>[64,65,135,136,108].includes(d.type)));
const filters=cloudParts.filter(d=>d.type===33),renderers=cloudParts.filter(d=>d.type===23);
check('Clouds share one 480-triangle mesh',filters.length===16&&filters.every(d=>d.text.includes('guid: '+guid('Weather/Meshes/SoftCloudCluster.asset')))&&/indexCount: 1440/.test(read('Weather/Meshes/SoftCloudCluster.asset')));
check('Cloud shadows and probe sampling disabled',renderers.length===16&&renderers.every(d=>scalar(d.text,'m_CastShadows')==='0'&&scalar(d.text,'m_ReceiveShadows')==='0'&&scalar(d.text,'m_LightProbeUsage')==='0'&&scalar(d.text,'m_ReflectionProbeUsage')==='0'));
check('Clouds share one material',renderers.every(d=>d.text.includes('guid: '+guid('Weather/Materials/SoftCloud.mat'))));
const linkedClouds=cycle?.text.match(/  clouds:\r?\n([\s\S]*?)(?=^  \w)/m)?.[1]||'';
check('All cloud transforms assigned to animation',cloudParts.filter(d=>d.type===4).every(d=>linkedClouds.includes('fileID: '+d.id)));
const stripSkyLink=t=>t.replace(/^  skyCycle:.*\r?\n/gm,'');
const changed=before.filter(d=>d.type!==4&&stripSkyLink(byID.get(d.id)?.text||'')!==stripSkyLink(d.text));
check('Pre-existing non-transform objects preserved except new UI link',changed.length===0,{checked:before.filter(d=>d.type!==4).length,changedIDs:changed.map(d=>d.id)});
check('Import completed once',read('WeatherCycleRequest.txt').trim()==='installed-live-visual-check-pending');
check('CPU validation report passed',read('Weather/WeatherCycleCheck.txt').includes('PASS: day/night boundaries')&&read('Weather/WeatherCycleCheck.txt').includes('PASS: UI'));
check('No ExecuteAlways, bake, GI refresh or extra render-camera calls in cycle',!/ExecuteAlways|DynamicGI\.|RenderTexture|\.Render\(/.test(read('Runtime/WellnessSkyCycle.cs')));
const result={ok:checks.every(c=>c.ok),method:'CPU-only saved-scene/reference checks; live visual appearance and frame rate not tested',checks};
console.log(JSON.stringify(result,null,2));if(!result.ok)process.exitCode=1;
