// Read-only saved-scene audit. No renderer, microphone, Unity process or Play session.
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const root='D:/Unity/HTH3 Project/Assets/TherapyGame',delivery='D:/Hack the Hill/Deliverables/TherapyGame';
const read=p=>fs.readFileSync(path.join(root,p),'utf8');
const parse=t=>[...t.matchAll(/^--- !u!(\d+) &(-?\d+)\r?\n([\s\S]*?)(?=^--- !u!|$(?![\s\S]))/gm)].map(m=>({type:+m[1],id:m[2],text:m[3]}));
const scalar=(t,k)=>t?.match(new RegExp('^  '+k+': (.*)$','m'))?.[1].trim();
const ref=(t,k)=>scalar(t,k)?.match(/fileID: (-?\d+)/)?.[1];
const guid=p=>read(p+'.meta').match(/guid: (\w+)/)[1];
const docs=parse(read('Scenes/TherapyRoom.unity')),before=parse(read('Exterior/Backups/TherapyRoom_BeforeNightDoorFix.unity'));
const byID=new Map(docs.map(d=>[d.id,d]));
const scripts=n=>docs.filter(d=>d.type===114&&d.text.includes('guid: '+guid('Runtime/'+n+'.cs')));
const checks=[];const check=(name,ok,detail)=>checks.push({name,ok:!!ok,...(detail===undefined?{}:{detail})});
const doors=scripts('WellnessDoor'),door=doors[0],fog=scripts('WellnessAtmosphere')[0],cycle=scripts('WellnessSkyCycle')[0];
const interactions=scripts('WellnessInteraction'),doorAction=interactions.find(d=>ref(d.text,'door')===door?.id);
check('Exactly one door toggle on the existing hinge',doors.length===1&&scalar(byID.get(ref(door?.text,'m_GameObject'))?.text,'m_Name')==='Open door hinge');
check('E interaction references the hinged door',doorAction&&ref(doorAction.text,'m_GameObject')===ref(door.text,'m_GameObject'));
check('Existing solid leaf and player capsule assigned',byID.get(ref(door?.text,'leaf'))?.type===65&&byID.get(ref(door?.text,'player'))?.type===143&&scalar(byID.get(ref(door?.text,'leaf'))?.text,'m_IsTrigger')==='0');
check('Gentle door speed and original open angle retained',scalar(door?.text,'openAngle')==='105'&&scalar(door?.text,'degreesPerSecond')==='70');
check('Indoor fog zero with garden transition retained',scalar(fog?.text,'density')==='0'&&scalar(fog?.text,'gardenTransition')==='1');
check('Cycle still drives the same atmosphere',ref(cycle?.text,'atmosphere')===fog?.id);
check('All original objects retained',before.filter(d=>d.type===1).every(d=>byID.has(d.id))&&docs.filter(d=>d.type===1).length===before.filter(d=>d.type===1).length);
const immutable=[4,20,23,33,64,65,104,108,135,136,143,157];
const changed=before.filter(d=>immutable.includes(d.type)&&byID.get(d.id)?.text!==d.text);
check('Existing transforms, colliders, renderers, lights and baked settings untouched',changed.length===0,{unexpectedChanges:changed.map(d=>({id:d.id,type:d.type}))});
const allowed=new Set([fog?.id,ref(door?.text,'m_GameObject')]);
const normalize=t=>t?.replace(/^  door: \{fileID: 0\}\r?\n/gm,'');
const otherChanges=before.filter(d=>!allowed.has(d.id)&&normalize(byID.get(d.id)?.text)!==normalize(d.text));
check('Unrelated scene data preserved',otherChanges.length===0,{unexpectedIDs:otherChanges.map(d=>d.id)});
check('All seven existing interactions plus door retained',interactions.length===8);
check('Weather rain and voice references intact',ref(scripts('WellnessVoiceChat')[0]?.text,'skyCycle')===cycle?.id&&ref(cycle?.text,'rain')===scripts('WellnessRain')[0]?.id&&ref(cycle?.text,'cloudDeck')===scripts('WellnessCloudDeck')[0]?.id);
const water=read('Exterior/Shaders/QuietPond.shader');
check('No crossing sine brightness lattice',!water.includes('sin(a) * sin(b)')&&!water.includes('tint +='));
check('Per-pixel water fog and filtered fading shadows',water.includes('ComputeFogFactorZ0ToFar(viewDepth)')&&water.includes('_SHADOWS_SOFT_LOW')&&water.includes('input.positionWS, half4(1,1,1,1)'));
check('CPU installation checks passed',read('Exterior/NightDoorCheck.txt').includes('PASS: door references; E prompt; closed leaf blocks rays from both sides'));
check('One-use gate completed',read('NightDoorFixRequest.txt').trim()==='installed-live-visual-check-pending');
const hash=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');
const edited=['Runtime/WellnessAtmosphere.cs','Runtime/WellnessDoor.cs','Runtime/WellnessInteraction.cs','Runtime/WellnessExplorer.cs','Exterior/Shaders/QuietPond.shader','Editor/TherapyNightDoorFix.cs'];
check('Live code and shader match compiled delivery',edited.every(p=>hash(path.join(root,p))===hash(path.join(delivery,p))));
const result={ok:checks.every(c=>c.ok),method:'CPU-only references and saved data; no live visual or performance verification',checks};
console.log(JSON.stringify(result,null,2));if(!result.ok)process.exitCode=1;
